# Generated by Django 4.2.1 on 2023-05-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_header_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='img',
            new_name='video',
        ),
    ]
