# Generated by Django 4.2.1 on 2023-05-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_img_header_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='img1',
            field=models.ImageField(default=0, upload_to='media', verbose_name='Img 1:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='img2',
            field=models.ImageField(default=0, upload_to='media', verbose_name='Img 2:'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='header',
            name='img3',
            field=models.ImageField(default=0, upload_to='media', verbose_name='Img 3:'),
            preserve_default=False,
        ),
    ]
