# Generated by Django 4.2.1 on 2023-05-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_header_title_img1_header_title_img2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=75, verbose_name='Title 1: ')),
                ('title2', models.CharField(max_length=75, verbose_name='Title 2 : ')),
                ('title3', models.CharField(max_length=75, verbose_name='Title 3 : ')),
                ('txt', models.TextField(verbose_name='Text: ')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
    ]
