# Generated by Django 4.2.1 on 2023-05-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='Img :')),
            ],
            options={
                'verbose_name': 'About photo',
                'verbose_name_plural': 'About photos',
            },
        ),
    ]
