# Generated by Django 4.2.1 on 2023-05-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_clientmail_facebook_alter_clientmail_gmail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmail',
            name='gmail',
            field=models.URLField(blank=True, null=True, verbose_name='Gmail :'),
        ),
    ]
