# Generated by Django 4.2.1 on 2023-05-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_clientmail_gmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutTitile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Title: ')),
                ('txt', models.TextField(verbose_name='Text: ')),
                ('name', models.CharField(max_length=75, verbose_name='Name: ')),
                ('profesion', models.CharField(max_length=75, verbose_name='Profesion: ')),
                ('img', models.ImageField(upload_to='media', verbose_name='Img :')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook: ')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram :')),
                ('gmail', models.URLField(blank=True, null=True, verbose_name='Gmail :')),
            ],
            options={
                'verbose_name': 'About Title',
                'verbose_name_plural': 'About Titles',
            },
        ),
        migrations.RenameModel(
            old_name='ClientMail',
            new_name='AboutClient',
        ),
        migrations.AlterModelOptions(
            name='aboutclient',
            options={'verbose_name': 'About Client', 'verbose_name_plural': 'About Clients'},
        ),
    ]
