# Generated by Django 4.2.1 on 2023-05-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_abouttitile_rename_clientmail_aboutclient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutclient',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='Whatsapp :'),
        ),
        migrations.AddField(
            model_name='abouttitile',
            name='whatsapp',
            field=models.URLField(blank=True, null=True, verbose_name='Whatsapp :'),
        ),
    ]
