# Generated by Django 4.2.1 on 2023-05-25 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_aboutclient_whatsapp_abouttitile_whatsapp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutClient',
            new_name='SpeakerInformation',
        ),
        migrations.RenameModel(
            old_name='AboutTitile',
            new_name='SpeakerTitile',
        ),
        migrations.AlterModelOptions(
            name='speakerinformation',
            options={'verbose_name': 'Speaker Information', 'verbose_name_plural': 'Speaker Informations'},
        ),
        migrations.AlterModelOptions(
            name='speakertitile',
            options={'verbose_name': 'Speaker Titile', 'verbose_name_plural': 'Speaker Titiles'},
        ),
    ]
