# Generated by Django 4.2.1 on 2023-05-25 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_schedulesdays'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulesInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Title: ')),
                ('txt', models.TextField(verbose_name='Text: ')),
                ('name', models.CharField(max_length=75, verbose_name='Name: ')),
                ('profesion', models.CharField(max_length=75, verbose_name='Profesion: ')),
                ('img', models.ImageField(upload_to='media', verbose_name='Img :')),
                ('hour1', models.DateTimeField(verbose_name='Hour 1: ')),
                ('hour2', models.DateTimeField(verbose_name='Hour 1: ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='main.schedulesdays')),
            ],
            options={
                'verbose_name': 'Schedule Information',
                'verbose_name_plural': 'Schedules Informations',
            },
        ),
    ]
