# Generated by Django 4.2.1 on 2023-05-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_schedulesinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesinformation',
            name='people_img',
            field=models.ImageField(default=0, upload_to='media', verbose_name='People img :'),
            preserve_default=False,
        ),
    ]
