# Generated by Django 4.2.1 on 2023-05-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_schedulesinformation_people_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulesinformation',
            name='hour1',
            field=models.TimeField(verbose_name='Hour 1: '),
        ),
        migrations.AlterField(
            model_name='schedulesinformation',
            name='hour2',
            field=models.TimeField(verbose_name='Hour 1: '),
        ),
    ]
