# Generated by Django 4.2.1 on 2023-05-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_schedulesinformation_hour1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesinformation',
            name='place',
            field=models.CharField(default=0, max_length=75, verbose_name='Place: '),
            preserve_default=False,
        ),
    ]
