# Generated by Django 4.2.1 on 2023-05-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_schedulesinformation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulesinformation',
            name='people_img',
            field=models.ImageField(blank=True, default=2, upload_to='media', verbose_name='People img :'),
            preserve_default=False,
        ),
    ]
