# Generated by Django 4.2.1 on 2023-05-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_pricing_pricingtitle_registertoday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulesinformation',
            name='people_img',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='People img :'),
        ),
    ]
