# Generated by Django 4.2.1 on 2023-05-25 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_venue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='emai',
            new_name='email',
        ),
    ]
