# Generated by Django 4.2.1 on 2023-05-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_rename_emai_venue_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Name: ')),
                ('email', models.EmailField(max_length=254, verbose_name='Email: ')),
                ('subject', models.TextField(verbose_name='Subject: ')),
                ('message', models.TextField(verbose_name='Subject: ')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
