# Generated by Django 4.2.1 on 2023-05-25 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_header_date2_alter_header_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='date',
            new_name='%d',
        ),
    ]
