# Generated by Django 4.2.1 on 2023-05-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_rename_date_header__d'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header',
            old_name='%d',
            new_name='date',
        ),
    ]
