# Generated by Django 4.2.1 on 2023-05-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_rename__d_header_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook: ')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram :')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='YouTube :')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Whatsapp :')),
            ],
            options={
                'verbose_name': 'FooterContact',
                'verbose_name_plural': 'FooterContact',
            },
        ),
    ]
