# Generated by Django 4.2.1 on 2023-05-27 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_footercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesinformation',
            name='people',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='main.speakerinformation'),
            preserve_default=False,
        ),
    ]
