# Generated by Django 4.2.1 on 2023-05-27 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_schedulesinformation_people'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulesinformation',
            name='img',
        ),
        migrations.RemoveField(
            model_name='schedulesinformation',
            name='people_img',
        ),
        migrations.RemoveField(
            model_name='schedulesinformation',
            name='profesion',
        ),
    ]
