# Generated by Django 4.2.1 on 2023-05-27 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_schedulesinformation_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulesinformation',
            name='img',
            field=models.ImageField(default=5, upload_to='media', verbose_name='Img :'),
            preserve_default=False,
        ),
    ]
